
# Put project images in static/images/3d/ or static/images/2d/.
# If image is empty, the gradient is used as the placeholder.

TOOLS_3D = ["ZBrush", "Blender", "Substance 3D Painter", "AccuRIG"]
TOOLS_2D = ["Clip Studio Paint", "Photoshop", "Adobe Illustrator", "Toon Boom Harmony"]

WORKS = [

    # ============================================================
    #                         3D PROJECTS
    # ============================================================

    {
        #1
        "title": "Vehicle Model",
        "slug": "vehicle-model",
        "category": "3d",
        "description": "A vehicle modeling project focused on form, proportions, and the presentation of a recognizable automotive design.",
        "tools": TOOLS_3D.copy(),
        "skills": ["Vehicle Modeling", "Hard Surface"],
        "image": "static/images/3d/Batmobil.png",
        "gradient": ["#ff5c38", "#a56bff"],
        "featured": True,
        "links": {"project": "", "demo": ""},
    },
    {
        #2
        "title": "Final Render Showcase",
        "slug": "final-render-showcase",
        "category": "3d",
        "description": "A finished 3D artwork showcasing the combined presentation of modeling, surface materials, lighting, and rendering.",
        "tools": TOOLS_3D.copy(),
        "skills": ["Sculpting", "Character Study", "Rendering", "Presentation"],
        "image": "static/images/3d/finished-version-3.png",
        "gradient": ["#38b6ff", "#a56bff"],
        "featured": True,
        "links": {"project": "", "demo": ""},
    },
    {
        #3
        "title": "GeoNode Trial",
        "slug": "geo-node-trial",
        "category": "3d",
        "description": "A Geometry Nodes experiment featuring three monkey-head models connected through a procedural setup in Blender.",
        "tools": TOOLS_3D.copy(),
        "skills": ["Texture"],
        "image": "static/images/3d/first-geo-node.png",
        "gradient": ["#a56bff", "#ff5c38"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #4
        "title": "Gut's Sword",
        "slug": "guts-sword",
        "category": "3d",
        "description": "A 3D recreation of Guts' sword from Berserk, focusing on the weapon's distinctive silhouette, proportions, and overall form.",
        "tools": TOOLS_3D.copy(),
        "skills": ["Prop Design"],
        "image": "static/images/3d/Guuts1.png",
        "gradient": ["#3ddc84", "#38b6ff"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #5
        "title": "A-Pose Rig",
        "slug": "a-pose-rig",
        "category": "3d",
        "description": "A female character model presented in an A-pose, exploring character proportions and preparation for a rigging workflow.",
        "tools": TOOLS_3D.copy(),
        "skills": ["Character Study", "Sculpting"],
        "image": "static/images/3d/hhsh1.png",
        "gradient": ["#ffb038", "#ff5c38"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #6
        "title": "Sub Machine Gun",
        "slug": "sub-machine-gun",
        "category": "3d",
        "description": "A high-poly submachine gun model emphasizing hard-surface forms, mechanical details, and presentation.",
        "tools": TOOLS_3D.copy(),
        "skills": ["Hard Surface", "Prop Design"],
        "image": "static/images/3d/High-poly-Gallahand.png",
        "gradient": ["#a56bff", "#38b6ff"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #7
        "title": "Duplex House",
        "slug": "duplex-house",
        "category": "3d",
        "description": "A 3D duplex house model exploring architectural forms, structural proportions, and the arrangement of building elements.",
        "tools": TOOLS_3D.copy(),
        "skills": ["Prop Design", "Environment Art"],
        "image": "static/images/3d/HOUSE.png",
        "gradient": ["#3ddc84", "#a56bff"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #8
        "title": "Another A-Pose Rig",
        "slug": "another-a-pose-rig",
        "category": "3d",
        "description": "A second female character model in an A-pose, continuing the exploration of character modeling and body proportions.",
        "tools": TOOLS_3D.copy(),
        "skills": ["Character Modelling", "Hard Surface"],
        "image": "static/images/3d/jd-2.png",
        "gradient": ["#38b6ff", "#3ddc84"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #9
        "title": "Fantasy Weapon",
        "slug": "fantasy-weapon",
        "category": "3d",
        "description": "A fantasy weapon concept developed in 3D, emphasizing silhouette, form, and distinctive visual details.",
        "tools": TOOLS_3D.copy(),
        "skills": ["Hard Surface", "Prop Design"],
        "image": "static/images/3d/knife-1.png",
        "gradient": ["#ffb038", "#3ddc84"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #10
        
        "title": "Stylised Hair Model",
        "slug": "stylised-hair-model",
        "category": "3d",
        "description": "A stylized female character study featuring a distinctive hairstyle, with an emphasis on shape, volume, and visual identity.",
        "tools": TOOLS_3D.copy(),
        "skills": ["Character Modeling", "Sculpting"],
        "image": "static/images/3d/Marat-4.png",
        "gradient": ["#38b6ff", "#ff5c38"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #11
        "title": "T Pose",
        "slug": "t-pose",
        "category": "3d",
        "description": "A female character model presented in a T-pose, providing a clear view of the character's overall proportions and anatomy.",
        "tools": TOOLS_3D.copy(),
        "skills": ["Sculpting", "Body Anatomy"],
        "image": "static/images/3d/murewa-1.png",
        "gradient": ["#a56bff", "#3ddc84"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #12
        "title": "Fantasy Sword",
        "slug": "fantasy-sword",
        "category": "3d",
        "description": "A fantasy sword model focused on blade proportions, handle design, and the visual details that define the weapon.",
        "tools": TOOLS_3D.copy(),
        "skills": ["Retopology", "Hard Surface", "Prop Design"],
        "image": "static/images/3d/new-sword-2.png",
        "gradient": ["#ff5c38", "#38b6ff"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #13
        "title": "Yoruba Sword",
        "slug": "yoruba-sword",
        "category": "3d",
        "description": "A 3D interpretation of a traditional Yoruba sword, exploring its form and translating its distinctive design into a digital model.",
        "tools": TOOLS_3D.copy(),
        "skills": ["Hard Surface", "Prop Design"],
        "image": "static/images/3d/olamide.png",
        "gradient": ["#a56bff", "#ffb038"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #14
        "title": "A-Pose Model",
        "slug": "a-pose-model",
        "category": "3d",
        "description": "A sculpted female character model presented in an A-pose, focusing on body proportions, silhouette, and character form.",
        "tools": TOOLS_3D.copy(),
        "skills": ["Character Modeling", "Sculpting"],
        "image": "static/images/3d/riggs.png",
        "gradient": ["#38b6ff", "#ffb038"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #15
        "title": "Character Pose Study",
        "slug": "character-pose-study",
        "category": "3d",
        "description": "A character presentation study exploring pose, body language, and the visual expression created by positioning the model.",
        "tools": TOOLS_3D.copy(),
        "skills": ["Rigging", "Positioning", "Rendering"],
        "image": "static/images/3d/RIGS-2.png",
        "gradient": ["#ff5c38", "#3ddc84"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #16
        "title": "ZBrush Character Sculpt",
        "slug": "zbrush-character-sculpt",
        "category": "3d",
        "description": "A character-sculpting study exploring the digital sculpting workflow in ZBrush and the development of a three-dimensional character form.",
        "tools": TOOLS_3D.copy(),
        "skills": ["3D Sculpting", "Character Study"],
        "image": "static/images/3d/zbrush-comparison-1.png",
        "gradient": ["#a56bff", "#38b6ff"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #17
        "title": "Stylized Creature",
        "slug": "stylized-creature",
        "category": "3d",
        "description": "A stylized creature model focused on distinctive shapes, character, and a visually recognizable silhouette.",
        "tools": TOOLS_3D.copy(),
        "skills": ["Creature Design", "Sculpting"],
        "image": "static/images/3d/ZOD.png",
        "gradient": ["#3ddc84", "#a56bff"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },


    # ============================================================
    #                         2D PROJECTS
    # ============================================================

    {
        #1
        "title": "Editorial Illustration",
        "slug": "editorial-illustration",
        "category": "2d",
        "description": "Illustration developed around a clear visual concept and editorial composition.",
        "tools": TOOLS_2D.copy(),
        "skills": ["Illustration", "Composition"],
        "image": "",
        "gradient": ["#ff5c38", "#ffb038"],
        "featured": True,
        "links": {"project": "", "demo": ""},
    },
    {
        #2
        "title": "Concept Character Sheet",
        "slug": "concept-character-sheet",
        "category": "2d",
        "description": "Character exploration showing shape language, design variations, and visual direction.",
        "tools": TOOLS_2D.copy(),
        "skills": ["Concept Art", "Character Design"],
        "image": "",
        "gradient": ["#ff5c38", "#a56bff"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #3
        "title": "Short Film Storyboard",
        "slug": "short-film-storyboard",
        "category": "2d",
        "description": "Storyboard sequence developed to communicate shots, composition, action, and pacing.",
        "tools": TOOLS_2D.copy(),
        "skills": ["Storyboarding", "Visual Development"],
        "image": "",
        "gradient": ["#38b6ff", "#3ddc84"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #4
        "title": "2D Animated Explainer",
        "slug": "2d-animated-explainer",
        "category": "2d",
        "description": "Short 2D animation focused on clear visual communication and motion.",
        "tools": TOOLS_2D.copy(),
        "skills": ["2D Animation", "Motion Design"],
        "image": "",
        "gradient": ["#a56bff", "#38b6ff"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #5
        "title": "Fantasy Landscape",
        "slug": "fantasy-landscape",
        "category": "2d",
        "description": "Fantasy landscape illustration exploring atmosphere, depth, and color.",
        "tools": TOOLS_2D.copy(),
        "skills": ["Environment Art", "Digital Painting"],
        "image": "",
        "gradient": ["#38b6ff", "#a56bff"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #6
        "title": "Character Portrait",
        "slug": "character-portrait",
        "category": "2d",
        "description": "Character portrait focused on expression, lighting, and visual storytelling.",
        "tools": TOOLS_2D.copy(),
        "skills": ["Portraiture", "Digital Painting"],
        "image": "",
        "gradient": ["#ff5c38", "#a56bff"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #7
        "title": "Comic Book Page",
        "slug": "comic-book-page",
        "category": "2d",
        "description": "Comic page combining sequential panels, readable action, and visual pacing.",
        "tools": TOOLS_2D.copy(),
        "skills": ["Comic Art", "Sequential Storytelling"],
        "image": "",
        "gradient": ["#ffb038", "#ff5c38"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #8
        "title": "Logo Design",
        "slug": "logo-design",
        "category": "2d",
        "description": "Logo concept exploring shape, typography, and brand recognition.",
        "tools": TOOLS_2D.copy(),
        "skills": ["Logo Design", "Vector Graphics"],
        "image": "",
        "gradient": ["#3ddc84", "#38b6ff"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #9
        "title": "Brand Identity",
        "slug": "brand-identity",
        "category": "2d",
        "description": "Visual identity exploration covering logo, color, typography, and graphic elements.",
        "tools": TOOLS_2D.copy(),
        "skills": ["Branding", "Graphic Design"],
        "image": "",
        "gradient": ["#a56bff", "#ff5c38"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #10
        "title": "Poster Design",
        "slug": "poster-design",
        "category": "2d",
        "description": "Poster design using hierarchy, typography, and composition to communicate a message.",
        "tools": TOOLS_2D.copy(),
        "skills": ["Poster Design", "Typography"],
        "image": "",
        "gradient": ["#38b6ff", "#ff5c38"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #11
        "title": "Book Cover Illustration",
        "slug": "book-cover-illustration",
        "category": "2d",
        "description": "Book cover concept combining illustration and typography to convey a story's tone.",
        "tools": TOOLS_2D.copy(),
        "skills": ["Cover Design", "Illustration"],
        "image": "",
        "gradient": ["#a56bff", "#ffb038"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #12
        "title": "Children's Book Illustration",
        "slug": "childrens-book-illustration",
        "category": "2d",
        "description": "Storybook illustration designed around expressive characters and approachable visuals.",
        "tools": TOOLS_2D.copy(),
        "skills": ["Storybook Art", "Character Illustration"],
        "image": "",
        "gradient": ["#3ddc84", "#ffb038"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #13
        "title": "Icon Set",
        "slug": "icon-set",
        "category": "2d",
        "description": "Consistent icon family built around a unified visual language.",
        "tools": TOOLS_2D.copy(),
        "skills": ["Icon Design", "Vector Graphics"],
        "image": "",
        "gradient": ["#38b6ff", "#3ddc84"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #14
        "title": "Infographic Design",
        "slug": "infographic-design",
        "category": "2d",
        "description": "Information-led graphic design that organizes facts into a clear visual narrative.",
        "tools": TOOLS_2D.copy(),
        "skills": ["Information Design", "Data Visualization"],
        "image": "",
        "gradient": ["#ff5c38", "#38b6ff"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #15
        "title": "Character Expression Sheet",
        "slug": "character-expression-sheet",
        "category": "2d",
        "description": "Expression sheet exploring facial emotion and character consistency.",
        "tools": TOOLS_2D.copy(),
        "skills": ["Character Design", "Expression"],
        "image": "",
        "gradient": ["#ffb038", "#a56bff"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #16
        "title": "Character Turnaround",
        "slug": "character-turnaround",
        "category": "2d",
        "description": "Character turnaround showing consistent proportions from multiple viewpoints.",
        "tools": TOOLS_2D.copy(),
        "skills": ["Character Design", "Model Sheets"],
        "image": "",
        "gradient": ["#38b6ff", "#a56bff"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #17
        "title": "Creature Concept Art",
        "slug": "creature-concept-art",
        "category": "2d",
        "description": "Creature design study exploring silhouette, anatomy, and visual identity.",
        "tools": TOOLS_2D.copy(),
        "skills": ["Creature Design", "Concept Art"],
        "image": "",
        "gradient": ["#3ddc84", "#a56bff"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #18
        "title": "Prop Design Sheet",
        "slug": "prop-design-sheet",
        "category": "2d",
        "description": "Prop concepts exploring shape, function, and visual consistency.",
        "tools": TOOLS_2D.copy(),
        "skills": ["Prop Design", "Concept Art"],
        "image": "",
        "gradient": ["#ff5c38", "#ffb038"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #19
        "title": "Environment Concept Art",
        "slug": "environment-concept-art",
        "category": "2d",
        "description": "Environment concept exploring mood, scale, and storytelling through scenery.",
        "tools": TOOLS_2D.copy(),
        "skills": ["Environment Design", "Concept Art"],
        "image": "",
        "gradient": ["#38b6ff", "#3ddc84"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #20
        "title": "Visual Development Sheet",
        "slug": "visual-development-sheet",
        "category": "2d",
        "description": "Visual development sheet establishing the look and feel of a creative project.",
        "tools": TOOLS_2D.copy(),
        "skills": ["Visual Development", "Color Design"],
        "image": "",
        "gradient": ["#a56bff", "#38b6ff"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #21
        "title": "Motion Graphics Titles",
        "slug": "motion-graphics-titles",
        "category": "2d",
        "description": "Animated title sequence combining typography, timing, and graphic transitions.",
        "tools": TOOLS_2D.copy(),
        "skills": ["Motion Graphics", "Typography"],
        "image": "",
        "gradient": ["#ff5c38", "#38b6ff"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #22
        "title": "Animated Character Loop",
        "slug": "animated-character-loop",
        "category": "2d",
        "description": "Short looping animation focused on readable movement and timing.",
        "tools": TOOLS_2D.copy(),
        "skills": ["2D Animation", "Character Animation"],
        "image": "",
        "gradient": ["#3ddc84", "#ff5c38"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #23
        "title": "Animated GIF",
        "slug": "animated-gif",
        "category": "2d",
        "description": "Compact animated sequence designed for looping playback and visual impact.",
        "tools": TOOLS_2D.copy(),
        "skills": ["Animation", "Timing"],
        "image": "",
        "gradient": ["#ffb038", "#38b6ff"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #24
        "title": "UI Illustration",
        "slug": "ui-illustration",
        "category": "2d",
        "description": "Custom illustration created to support a digital product's visual language.",
        "tools": TOOLS_2D.copy(),
        "skills": ["Product Illustration", "Vector Art"],
        "image": "",
        "gradient": ["#a56bff", "#3ddc84"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #25
        "title": "App Onboarding Illustrations",
        "slug": "app-onboarding-illustrations",
        "category": "2d",
        "description": "Illustration set designed to guide users through an app onboarding experience.",
        "tools": TOOLS_2D.copy(),
        "skills": ["Product Illustration", "Visual Storytelling"],
        "image": "",
        "gradient": ["#38b6ff", "#ffb038"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #26
        "title": "Pattern Design",
        "slug": "pattern-design",
        "category": "2d",
        "description": "Repeat pattern exploring rhythm, color, and cohesive decorative motifs.",
        "tools": TOOLS_2D.copy(),
        "skills": ["Pattern Design", "Surface Design"],
        "image": "",
        "gradient": ["#ff5c38", "#a56bff"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #27
        "title": "Textile Print",
        "slug": "textile-print",
        "category": "2d",
        "description": "Textile print concept built from repeatable shapes and a coordinated palette.",
        "tools": TOOLS_2D.copy(),
        "skills": ["Textile Design", "Pattern Making"],
        "image": "",
        "gradient": ["#3ddc84", "#38b6ff"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #28
        "title": "Album Cover",
        "slug": "album-cover",
        "category": "2d",
        "description": "Album artwork developed to reflect a musical identity and mood.",
        "tools": TOOLS_2D.copy(),
        "skills": ["Cover Art", "Graphic Design"],
        "image": "",
        "gradient": ["#a56bff", "#ff5c38"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #29
        "title": "Event Poster",
        "slug": "event-poster",
        "category": "2d",
        "description": "Event poster using typography, hierarchy, and imagery to communicate key details.",
        "tools": TOOLS_2D.copy(),
        "skills": ["Poster Design", "Typography"],
        "image": "",
        "gradient": ["#ffb038", "#3ddc84"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #30
        "title": "Social Media Campaign",
        "slug": "social-media-campaign",
        "category": "2d",
        "description": "Coordinated social graphics built around a consistent campaign visual identity.",
        "tools": TOOLS_2D.copy(),
        "skills": ["Social Media Design", "Brand Consistency"],
        "image": "",
        "gradient": ["#38b6ff", "#ff5c38"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #31
        "title": "Magazine Layout",
        "slug": "magazine-layout",
        "category": "2d",
        "description": "Editorial layout focused on typography, page hierarchy, and image placement.",
        "tools": TOOLS_2D.copy(),
        "skills": ["Editorial Design", "Layout"],
        "image": "",
        "gradient": ["#3ddc84", "#a56bff"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #32
        "title": "Typography Poster",
        "slug": "typography-poster",
        "category": "2d",
        "description": "Type-led poster exploring letterforms, scale, and visual hierarchy.",
        "tools": TOOLS_2D.copy(),
        "skills": ["Typography", "Graphic Design"],
        "image": "",
        "gradient": ["#ff5c38", "#38b6ff"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #33
        "title": "Vector Illustration",
        "slug": "vector-illustration",
        "category": "2d",
        "description": "Vector illustration using clean shapes, controlled color, and scalable artwork.",
        "tools": TOOLS_2D.copy(),
        "skills": ["Vector Art", "Illustration"],
        "image": "",
        "gradient": ["#a56bff", "#ffb038"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #34
        "title": "Minimalist Illustration",
        "slug": "minimalist-illustration",
        "category": "2d",
        "description": "Minimalist artwork using simplified forms and restrained visual elements.",
        "tools": TOOLS_2D.copy(),
        "skills": ["Minimalism", "Composition"],
        "image": "",
        "gradient": ["#38b6ff", "#a56bff"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #35
        "title": "Ink Drawing",
        "slug": "ink-drawing",
        "category": "2d",
        "description": "Ink drawing exploring line quality, contrast, and mark-making.",
        "tools": TOOLS_2D.copy(),
        "skills": ["Drawing", "Line Art"],
        "image": "",
        "gradient": ["#ffb038", "#ff5c38"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #36
        "title": "Pencil Illustration",
        "slug": "pencil-illustration",
        "category": "2d",
        "description": "Pencil study focused on tonal range, texture, and observation.",
        "tools": TOOLS_2D.copy(),
        "skills": ["Drawing", "Shading"],
        "image": "",
        "gradient": ["#3ddc84", "#a56bff"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #37
        "title": "Watercolor Study",
        "slug": "watercolor-study",
        "category": "2d",
        "description": "Watercolor study exploring transparent washes, edges, and color mixing.",
        "tools": TOOLS_2D.copy(),
        "skills": ["Traditional Painting", "Color"],
        "image": "",
        "gradient": ["#38b6ff", "#3ddc84"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #38
        "title": "Digital Painting Study",
        "slug": "digital-painting-study",
        "category": "2d",
        "description": "Digital painting study exploring values, brushwork, and color relationships.",
        "tools": TOOLS_2D.copy(),
        "skills": ["Digital Painting", "Color Theory"],
        "image": "",
        "gradient": ["#a56bff", "#38b6ff"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #39
        "title": "Sequential Art Study",
        "slug": "sequential-art-study",
        "category": "2d",
        "description": "Sequential artwork exploring panel transitions and visual storytelling.",
        "tools": TOOLS_2D.copy(),
        "skills": ["Sequential Art", "Storytelling"],
        "image": "",
        "gradient": ["#ff5c38", "#3ddc84"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #40
        "title": "Storyboard Animatic",
        "slug": "storyboard-animatic",
        "category": "2d",
        "description": "Timed storyboard sequence used to explore pacing, shot flow, and narrative clarity.",
        "tools": TOOLS_2D.copy(),
        "skills": ["Storyboarding", "Editing"],
        "image": "",
        "gradient": ["#ffb038", "#38b6ff"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #41
        "title": "Visual Development Color Keys",
        "slug": "visual-development-color-keys",
        "category": "2d",
        "description": "Color keys exploring lighting, mood, and palette choices across a scene.",
        "tools": TOOLS_2D.copy(),
        "skills": ["Color Scripting", "Visual Development"],
        "image": "",
        "gradient": ["#3ddc84", "#ff5c38"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },
    {
        #42
        "title": "Personal Art Collection",
        "slug": "personal-art-collection",
        "category": "2d",
        "description": "A curated collection of 2D artwork showcasing range, experimentation, and visual style.",
        "tools": TOOLS_2D.copy(),
        "skills": ["Illustration", "Visual Storytelling"],
        "image": "",
        "gradient": ["#a56bff", "#ff5c38"],
        "featured": False,
        "links": {"project": "", "demo": ""},
    },

]